{ pkgs, ... }:

{
  # Used to find the project root
  projectRootFile = "flake.nix";

  # Enable formatters
  programs.nixpkgs-fmt.enable = true;
  programs.prettier.enable = true;

  # Override the default settings generated by the above option
  settings.formatter.prettier.excludes = [ "themes/*" ];
}
